<?xml version="1.0"?>
<!-- Try to validate this document at: https://xmlvalidation.com/ -->
<!DOCTYPE BusinessCard [
<!-- BusinessCard has to contain a Name, 1 or more phone and 0 or more email -->
<!ELEMENT BusinessCard (Name, phone+, email?)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!-- The attribute of phone is required and has to be one of these -->
<!ATTLIST phone type (mobile | fax | work | home) #REQUIRED >
<!ELEMENT email (#PCDATA)>
]>
<BusinessCard>
	<Name>Joe Marini</Name>
	<phone type="mobile">(415) 555-4567</phone>
	<phone type="work">(800) 555-9876</phone>
	<phone type="fax">(510) 555-1234</phone>
	<phone type="home">(425) 555-8989</phone>
	<email>joe@joe.com</email>
</BusinessCard>
